# Generated by Django 5.0.6 on 2024-05-13 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название посещенного места')),
                ('description', models.CharField(max_length=400, verbose_name='Описание посещенного места')),
                ('longitude', models.FloatField(verbose_name='Широта посещенного места')),
                ('latitude', models.FloatField(verbose_name='Долгота посещенного места')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Посещенное место',
                'verbose_name_plural': 'Посещенные места',
                'db_table': 'place',
            },
        ),
        migrations.CreateModel(
            name='UserImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Изображение пользователя',
                'verbose_name_plural': 'Изображении пользователей',
                'db_table': 'user_image',
            },
        ),
    ]
